project/accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import (
    login_required, permission_required
)
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', login_required(views.LogoutView.as_view()), name='logout'),
    path('registration/', views.UserRegister.as_view(), name='user_register'),
    path('registration/done', views.UserRegisterDone.as_view(), name='user_register_done'),
    path('registration/complete/<token>', views.UserRegisterComplete.as_view(), name='user_register_complete'),
    path('password_change/', login_required(views.PasswordChange.as_view()), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('upload/', views.upload_file, name='upload'),
    path('month/<int:year>/<int:month>/', login_required(views.MonthCalendar.as_view()), name='month'),
    path('shift/<int:year>/<int:month>/<int:day>/', login_required(views.ShiftView.as_view()), name='shift'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, BaseUserManager
)
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.core.validators import FileExtensionValidator
import os


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('メールアドレスを入力してください')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', False)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_active=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    user_id = models.AutoField(primary_key=True, unique=True)
    email = models.EmailField(_('メールアドレス'),
                              max_length=128, unique=True,
                              help_text=_('通知を受け取りたいメールアドレスを入力'),
                              )
    first_name = models.CharField(_('名前'), max_length=10)
    last_name = models.CharField(_('名字'), max_length=10)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Send an email to this user
        """

        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.last_name + ' ' + self.first_name


class PDFFile(models.Model):

    attach = models.FileField(
        verbose_name='shift',
        upload_to='uploads/%Y/%m/%d/',
        validators=[FileExtensionValidator(['pdf', ])],
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

    def get_filename(self):
        return os.path.basename(self.attach.name)


class Shift(models.Model):

    pdf_id = models.ForeignKey(PDFFile, on_delete=models.CASCADE, related_name='pdf')
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    day = models.DateTimeField(_('日付'))
    segment = models.CharField(_('コマ'), max_length=1)
    student_name = models.CharField(_('生徒名'), max_length=10)
    subject_name = models.CharField(_('教科名'), max_length=10)
    student_grade = models.CharField(_('学年'), max_length=10)

project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, PasswordChangeForm
)
from .models import User, PDFFile


class RegistrationForm(UserCreationForm):
    """
    ユーザ登録フォーム
    """

    last_name = forms.CharField(max_length=10, required=True,
                                widget=forms.TextInput(
                                    attrs={'placeholder': '名字'}
                                ))
    first_name = forms.CharField(max_length=10, required=True,
                                 widget=forms.TextInput(
                                     attrs={'placeholder': '名前'}
                                 ))
    email = forms.EmailField(max_length=50, required=True,
                             widget=forms.EmailInput(
                                 attrs={'placeholder': 'メールアドレス'}
                             ))
    password1 = forms.CharField(max_length=30, required=True,
                                widget=forms.PasswordInput(
                                    attrs={'placeholder': 'パスワード'}
                                ))
    password2 = forms.CharField(max_length=30, required=True,
                                widget=forms.PasswordInput(
                                    attrs={'placeholder': 'パスワード(確認用)'}
                                ))

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'email')
        widgets = {
            'password': forms.PasswordInput()
        }

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    """
    ログインフォーム
    """

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class MyPasswordChangeForm(PasswordChangeForm):
    """
    パスワード変更フォーム
    """

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UploadFileForm(forms.ModelForm):

    class Meta:
        model = PDFFile
        fields = ['attach', ]

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)
        for field in self.fields.values():
            field.widget.attrs['accept'] = 'application/pdf'
            field.widget.attrs['style'] = 'display:none'

project/accounts/views.py
import calendar
from collections import deque
import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login
from django.contrib.auth import login
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.signing import dumps, loads
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import generic
from .models import User, PDFFile, Shift
from .forms import (
    LoginForm, RegistrationForm, MyPasswordChangeForm, UploadFileForm
)
from accounts.tasks import shiftregistrations
from project.settings import MEDIA_ROOT


class Index(generic.TemplateView):
    template_name = 'accounts/index.html'


class Login(LoginView):
    """
    ログインビュー
    """

    form_class = LoginForm
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, 'ログインしました'
        )
        return result


class Logout(LoginRequiredMixin, LogoutView):
    """
    ログアウトページ
    """

    template_name = 'accounts/index.html'


class UserRegister(generic.CreateView):
    """
    ユーザ仮登録
    """

    template_name = 'accounts/registration.html'
    form_class = RegistrationForm

    def form_valid(self, form):
        """
        仮登録と本登録メールの発行
        """

        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user
        }
        subject_template = get_template('accounts/mail_template/register/subject.txt')
        subject = subject_template.render(context)
        subject = subject.replace('\n', '')

        message_template = get_template('accounts/mail_template/register/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('accounts:user_register_done')


class UserRegisterDone(generic.TemplateView):
    """
    ユーザ仮登録をした
    """
    template_name = 'accounts/registration_done.html'


class UserRegisterComplete(generic.TemplateView):
    """
    メール内URLアクセス後のユーザ本登録
    """

    template_name = 'accounts/registration_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60 * 60 * 24)

    def get(self, request, **kargs):
        """
        tokenが正しければ本登録
        """
        token = kargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
        # timeout
        except SignatureExpired:
            return HttpResponseBadRequest()
        # token misses
        except BadSignature:
            return HttpResponseBadRequest

        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoenNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 本登録
                    user.is_active = True
                    user.save()
                    return super().get(request, **kargs)
        return HttpResponseBadRequest()


class PasswordChange(PasswordChangeView):
    """
    パスワード変更ビュー
    """

    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """
    パスワード変更完了ビュー
    """

    template_name = 'accounts/password_change_done.html'


def upload_file(request):
    """
    シフトアップロードビュー
    """

    if not request.user.is_superuser:
        return redirect('accounts:index')
    if request.method == 'POST':
        form = UploadFileForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            # ファイル処理
            pdf = form.save()
            shiftregistrations.delay(pdf.pk, MEDIA_ROOT + '/' + str(pdf.attach))
            messages.success(
                request, 'シフトを登録しました．反映にしばらく時間がかかります'
            )
            return redirect('accounts:index')
    else:
        form = UploadFileForm()
    return render(request, 'accounts/upload_pdf.html', {'form': form})


class BaseCalendarMixin:
    """
    Calendar Mixin super class
    """

    first_weekday = 6
    week_names = ['月', '火', '水', '木', '金', '土', '日']

    def setup(self):
        self._calendar = calendar.Calendar(self.first_weekday)

    def get_week_names(self):
        week_names = deque(self.week_names)
        week_names.rotate(-self.first_weekday)
        return week_names


class MonthCalendarMixin(BaseCalendarMixin):
    """
    Month Calendar Mixin
    """

    @staticmethod
    def get_previous_month(date):
        """
        return previous month
        """

        if date.month == 1:
            return date.replace(year=date.year - 1, month=12, day=1)
        return date.replace(month=date.month - 1, day=1)

    @staticmethod
    def get_next_month(date):
        """
        return next month
        """

        if date.month == 12:
            return date.replace(year=date.year + 1, month=1, day=1)
        return date.replace(month=date.month + 1, day=1)

    def get_current_month(self):
        """
        return current month
        """

        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        if month and year:
            month = datetime.date(year=int(year), month=int(month), day=1)
        else:
            month = datetime.date.today().replace(day=1)
        return month

    def get_month_days(self, date):
        return self._calendar.monthdatescalendar(date.year, date.month)

    def get_month_shifts(self, days, user):
        """
        return shifts in days
        """

        day_with_shifts = []
        for week in days:
            week_shifts = []
            for day in week:
                lookup = {'day': day, 'user_id': user}
                queryset = Shift.objects.filter(**lookup)
                segments = list(sorted(set([q.segment for q in queryset])))
                # シフト順の調整
                for s in ['Z', 'Y', 'X']:
                    if s in segments:
                        segments.remove(s)
                        segments.insert(0, s)
                week_shifts.append((day, "".join(segments)))
            day_with_shifts.append(week_shifts)
        return day_with_shifts

    def get_month_calendar(self, user):
        """
        return month calendar information
        """

        self.setup()
        current_month = self.get_current_month()
        calendar_data = {
            'now': datetime.date.today(),
            'days': self.get_month_days(current_month),
            'current': current_month,
            'previous': self.get_previous_month(current_month),
            'next': self.get_next_month(current_month),
            'week_names': self.get_week_names(),
        }
        calendar_data['days'] = self.get_month_shifts(calendar_data['days'], user)
        return calendar_data


class MonthCalendar(MonthCalendarMixin, generic.TemplateView):
    """
    Month Calendar View
    """

    template_name = 'accounts/month.html'

    def get_context_data(self, user, **kwargs):
        context = super().get_context_data(**kwargs)
        context['month'] = self.get_month_calendar(user)
        return context

    def get(self, request, **kwargs):
        context = self.get_context_data(user=request.user)
        return self.render_to_response(context)


class ShiftView(generic.TemplateView):
    """
    Shift View in a day
    """

    template_name = 'accounts/shift.html'

    def get_context_data(self, user, **kwargs):
        context = super().get_context_data(**kwargs)
        year = kwargs.get('year')
        month = kwargs.get('month')
        day = kwargs.get('day')
        segment = ('X', 'Y', 'Z', 'A', 'B', 'C', 'D')
        context['shift'] = {}
        for s in segment:
            shifts = Shift.objects.filter(user_id=user, day=datetime.date(year=year, month=month, day=day), segment=s)
            if len(shifts) > 0:
                context['shift'][s] = shifts
        return context

    def get(self, request, **kwargs):
        context = self.get_context_data(user=request.user, **kwargs)
        print(context)
        return self.render_to_response(context)

project/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="keywords" content>
        <meta http-equiv="X-UA-Compatible" content ="IE=edge" />
        <meta name="description" content="
        This Application maneges shifts of private school."
                                 >
                                 <title>PrivateSchoolWebApp</title>
                                 <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
                                 <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
    </head>
    <body>
        <div class="bmd-layout-container bmd-drawer-f-l bmd-drawer-overlay">
            <header class="bmd-layout-header">
                <div class="navbar navbar-light bg-dark navbar-dark mynav">

                    <button type="button" class="navbar-toggler" data-toggle="drawer" data-target="#dw-s1" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle drawer</span>
                        <i class="navbar-toggler-icon"></i>
                    </button>
                    <div class="d-none d-lg-block d-md-block">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link text-light" href="/accounts/">Top</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" href="/accounts/month/{% now "o/n" %}">シフト確認</a>
                            </li>
                            {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link text-light" href="/accounts/upload">シフトアップロード</a>
                            </li>
                            {% endif %}

                        </ul>
                    </div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if user.is_authenticated %}
                            {{ user.last_name }} {{ user.first_name }} 先生
                            {% else %}
                            ゲストユーザ
                            {% endif %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            {% if not user.is_authenticated %}
                            <a class="dropdown-item" href="/accounts/login/">ログイン</a>
                            <a class="dropdown-item" href="/accounts/registration/">ユーザ登録</a>
                            {% else %}
                            <a class="dropdown-item" href="/accounts/logout/">ログアウト</a>
                            <a class="dropdown-item" href="/accounts/password_change/">パスワード変更</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </header>
            <div id="dw-s1" class="bmd-layout-drawer bg-faded">
                <header>
                    <a class="navbar-brand">Menu</a>
                </header>
                <ul class="list-group">
                    <a class="list-group-item" href="/accounts/">Top</a>
                    <a class="list-group-item" href="/accounts/month/{% now "o/n" %}">シフト確認</a>
                    {% if user.is_superuser %}
                    <a class="list-group-item" href="/accounts/upload">シフトアップロード</a>
                    {% endif %}
                </ul>
            </div>
            <main class="bmd-layout-content center" role="main">
                <div class="container-fluid">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-success">{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                        {% block content %}{% endblock %}
                </div>
            </main>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

        <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
    </body>
</html>

project/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% block content %}

<div class="container">
    <section class="jumbotron text-center">
        <div class="container">
            <h4 class="jumbotron-heading">講師用アプリ</h4>
            <p class="lead text-muted">
            塾業務効率化アプリ</p>
            <p>
            {% if user.is_authenticated %}
            <a href="/accounts/logout/" class="btn btn-danger my-2">Logout</a>
            {% else %}
            <a href="/accounts/login/" class="btn btn-success my-2">Login</a>
            <a href="/accounts/registration/" class="btn btn-secondary my-2">新規登録</a>
            {% endif %}
            </p>
        </div>
    </section>
</div>

<div class="container">
    <div class="row">
          <div class="col-md-4 bg-light mx-2 py-2">
            <h4>シフト確認</h4>
            <p>カレンダー形式でシフトの確認ができます．カレンダー上で日付を選択すると，担当するコマの詳細情報も確認できます．</p>
            <p><a class="btn btn-secondary" href="/accounts/month/{% now "o/n" %}" role="button">View details »</a></p>
          </div>
          {% if user.is_superuser %}
          <div class="col-md-4 bg-light mx-2">
            <h4>シフトアップロード(室長限定)</h4>
            <p>pdf形式のシフトをアップロードすることで，自動で講師の方々のカレンダーにシフトを登録することができます．また，登録したシフトを講師の方々に通知することもできます．</p>
            <p><a class="btn btn-secondary" href="/accounts/upload/" role="button">View details »</a></p>
          </div>
          {% endif %}
    </div>
</div>

{% endblock %}

project/accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block content %}
<form class="form-signin" action="" method="POST">
    <h1 class="h3 mb-3 font-weight-normal text-center">ログイン</h1>
    <div class="form-label-group mx-auto">
        {% if form.non_field_errors %}
            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
        <div class="form-group bmd-form-group">
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-raised btn-block">ログイン</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
</form>

<p class="mx-auto">
<a href="/accounts/registration">新規登録</a>
</p>
{% endblock %}

project/accounts/templates/accounts/month.html
{% extends "accounts/base.html" %}
{% block content %}
<h1 class="h3 mb-3 font-weight-normal text-center">シフト確認</h1>
<div class="mt-3">
    <a href="{% url 'accounts:month' month.previous.year month.previous.month %}">前月</a>
    {{ month.current | date:"Y年n月" }}
    <a href="{% url 'accounts:month' month.next.year month.next.month %}">次月</a>
    <table class="table">
        <thead>
            <tr>
                {% for w in month.week_names %}
                <th>{{ w }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for week in month.days %}
            <tr>
                {% for day, shift in week %}
                {% if shift != "" %}
                <td class="table-info col-xs-7", style="width: 11vw; height: 65px; padding:.1rem;">
                {% else %}
                <td class="col-xs-7" style="width: 11vw; height: 65px; padding:.1rem;">
                {% endif %}
                <small>
                {% if month.current.month != day.month %}
                <div class="text-muted">{{ day | date:"j" }}</div>
                {% else %}
                {{ day.day }}
                {% endif %}
                </small>
                <p>
                <a href="/accounts/shift/{{ day | date:"o/n/j/" }}"style="font-size:60%;">{{ shift }}</a>
                </p>
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

project/accounts/templates/accounts/password_change.html
{% extends "accounts/base.html" %}
{% block content %}
<form class="form-signin" action="" method="POST">
    <h1 class="h3 mb-3 font-weight-normal text-center">パスワード変更</h1>
    <div class="form-label-group mx-auto">
        {% if form.non_field_errors %}
            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
        <div class="form-group">
            {{ field }}
            {% for error in field.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-block btn-raised btn-secondary" >パスワード変更</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
</form>
{% endblock %}

project/accounts/templates/accounts/password_change_done.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    パスワードを変更しました．<br>
    <a class="btn" href="{% url 'accounts:login' %}">ログイン</a>
</p>
{% endblock %}

project/accounts/templates/accounts/registration.html
{% extends "accounts/base.html" %}
{% block content %}
<form class="form-signin" action="" method="POST">
    <h1 class="h3 mb-3 font-weight-normal text-center">ユーザ登録</h1>
    <div class="form-label-group mx-auto">
        {% if form.non_field_errors %}
            <div class="alert alert-danger">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
        <div class="form-group">
            {{ field }}
            {% for error in field.errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-raised btn-block">登録</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
</form>
{% endblock %}

project/accounts/templates/accounts/registration_complete.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    本登録が完了しました．<br>
    登録されたメールアドレスとパスワードでログインしてください．<br>
    <a class="btn" href="{% url 'accounts:login' %}">ログイン</a>
</p>
{% endblock %}

project/accounts/templates/accounts/registration_done.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました．
    まだ，会員登録は完了していません．
    会員登録確認メールに記載されているリンクから本登録をお願いします．
</p>
{% endblock %}

project/accounts/templates/accounts/shift.html
{% extends 'accounts/base.html' %}
{% block content %}

{% for segment, value in shift.items %}
{% if value == value %}
<div class="container">
<p>
{{ segment }}
</p>
<table class="table table-hover table-sm" style="table-layout:fixed;">
    <thead>
        <tr>
            <th scope="col" style="width:15vw;">生徒名</th>
            <th scope="col" style="width:10vw;">教科</th>
            <th scope="col" style="width:10vw;">学年</th>
        </tr>
    </thead>
{% for v in value %}
    <tbody>
        <tr>
            <td>{{ v.student_name }}</td>
            <td>{{ v.subject_name }}</td>
            <td>{{ v.student_grade }}</td>
        </tr>
    </tbody>
{% endfor %}
</table>
</div>
{% endif %}
{% endfor %}


{% endblock %}

project/accounts/templates/accounts/upload_pdf.html
{% extends 'accounts/base.html' %}
{% block content %}

<div class="container mx-auto">
    <h1 class="h4 mb-3 font-weight-normal text-center">シフトアップロード</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}" class="btn btn-raised btn-primary">
                シフトファイル選択
                {{ field }}
            </label>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="submit" class="btn btn-raised">
        </div>
    </form>
</div>


{% endblock %}